#:schema node_modules/wrangler/config-schema.json
name = "milkyway-japan"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"


# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "milkyway-assets"

# Vars
[vars]
ENVIRONMENT = "production"
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET"
