#:schema node_modules/wrangler/config-schema.json
name = "milkyway-japan"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "milkyway-db"
database_id = "e6e6-4afa-8922-0e1c39622cf7" # Placeholder ID

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "milkyway-assets"

# Vars
[vars]
ENVIRONMENT = "production"
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET"
